version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_inversiones
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inversiones
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db_data:
